service: mtglm-infrastructure

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128

resources:
  Resources:
    RoleGodMode: ${file(common/iam.yml)}
    CodeBuildWeb: ${file(codebuild/web.yml)}
